// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm-SO0rgzBVmdDJaC22Zvf4_ewrD0am3U',
    appId: '1:1047863896249:web:cec1463e69cdcc632e5368',
    messagingSenderId: '1047863896249',
    projectId: 'wallet-a3c81',
    authDomain: 'wallet-a3c81.firebaseapp.com',
    storageBucket: 'wallet-a3c81.appspot.com',
    measurementId: 'G-FC1XJZ04VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4TaNRpH-PGQS4HOK-RUrBGVoamYEM3X4',
    appId: '1:1047863896249:android:e34caffbe203f8462e5368',
    messagingSenderId: '1047863896249',
    projectId: 'wallet-a3c81',
    storageBucket: 'wallet-a3c81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_UWxdTuTldy5Bf1bY5ocZW1iMB8mcL1s',
    appId: '1:1047863896249:ios:093fbc23c12661392e5368',
    messagingSenderId: '1047863896249',
    projectId: 'wallet-a3c81',
    storageBucket: 'wallet-a3c81.appspot.com',
    iosClientId: '1047863896249-4p6vkliifk0n2uqjhva681d18gndp67a.apps.googleusercontent.com',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_UWxdTuTldy5Bf1bY5ocZW1iMB8mcL1s',
    appId: '1:1047863896249:ios:093fbc23c12661392e5368',
    messagingSenderId: '1047863896249',
    projectId: 'wallet-a3c81',
    storageBucket: 'wallet-a3c81.appspot.com',
    iosClientId: '1047863896249-4p6vkliifk0n2uqjhva681d18gndp67a.apps.googleusercontent.com',
    iosBundleId: 'com.example.appProject',
  );
}
